# Default values for vid-recipe-gen.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/tk-hap/video-recipe-gen-flask
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "9e5619c197711159fdc6b5210c0cb652624ca2cb"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

config:
  redisHost : "redis-master.tk.svc.cluster.local" #K8s Service
  redisPort : 6379
  requestLimit : 5
  requestTimeoutSecs : 86400
  maxVideoLength: "PT45M"
  logLevel: "INFO"

apiKeys:
  openAiApiKey: ""
  youtubeApiKey: ""

ingress:
  certificateArn: "arn:aws:acm:ap-southeast-2:223061654492:certificate/dd6bfe6f-2002-49cc-a8e0-fddb57b18b6c"