apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vid-recipe-gen-flask
spec:
  selector:
    app: vid-recipe-gen-flask
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080