name: CI - Ruff Linting
on: [ push, pull_request ]
jobs:
  lint-fmt:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./flask

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Ruff
        run: pip install ruff

      - name: Lint
        run: ruff check --fix

      - name: Format
        run: ruff format

